---

- include_tasks: install.deb.yml
  when: ansible_os_family == "Debian" and not backup_remove

- include_tasks: install.red.yml
  when: ansible_os_family == "RedHat" and not backup_remove

- include_tasks: configure.yml
  when: not backup_remove

- include_tasks: remove.yml
  when: backup_remove
