---

- include_vars: "{{ ansible_distribution }}.yml"

- name: Add duplicity repository
  apt_repository:
    repo: ppa:duplicity-team/ppa
    state: present
    update_cache: yes
  when: backup_duplicity_ppa

- set_fact:
    backup_duplicity_pkg: "{{ backup_duplicity_pkg }}={{ backup_duplicity_version }}"
  when: backup_duplicity_version

- name: Install core dependencies
  apt:
    name:
      - cron
      - gzip
      - duply
      - "{{ backup_duplicity_pkg }}"
    state: present

- name: Install backup profile dependencies
  apt:
    name: "{{ backup_scheme_deps[item.target | default(backup_target) | urlsplit('scheme')] }}"
    state: present
  loop: "{{ backup_profiles }}"
  when: backup_scheme_deps[item.target | default(backup_target) | urlsplit('scheme')] is defined
